import nodemailer from "nodemailer";

// Configure the email transporter using Gmail
const transporter = nodemailer.createTransport({
	service: "gmail",
	auth: {
		user: process.env.EMAIL_USER,
		pass: process.env.EMAIL_PASS,
	},
});

export async function sendJobDigest(userEmail: string, jobs: any[]) {
	if (jobs.length === 0) return;

	const date = new Date().toLocaleDateString("en-GB", {
		weekday: "long",
		day: "numeric",
		month: "long",
		year: "numeric",
	});

	const t1 = jobs.filter((j) => j.tier === 1);
	const t2 = jobs.filter((j) => j.tier === 2);
	const t3 = jobs.filter((j) => j.tier === 3); // NEW: Now we are successfully gathering Tier 3 jobs!

	const formatJobs = (jobList: any[], tierColor: string) => {
		return jobList
			.map(
				(j) => `
      <div style="border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 16px; border-left: 4px solid ${tierColor}; background-color: #ffffff;">
        <div style="font-weight: 800; color: #0f172a; font-size: 16px; font-family: Helvetica, Arial, sans-serif;">
          ${j.title || j.role}
        </div>
        <div style="color: #0369a1; font-size: 14px; font-weight: 700; margin: 8px 0; font-family: Helvetica, Arial, sans-serif;">
          ${j.company} &bull; ${j.loc}
        </div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top: 16px;">
          <tr>
            <td align="left" style="font-size: 13px; color: #64748b; font-family: Helvetica, Arial, sans-serif; font-weight: 600;">
              Match Score: <strong style="color: ${tierColor}; font-size: 14px;">${j.score}%</strong>
            </td>
            <td align="right">
              <a href="${j.url}" style="color: #0058bc; font-size: 13px; font-weight: 700; text-decoration: none; font-family: Helvetica, Arial, sans-serif;">
                Apply Online &rarr;
              </a>
            </td>
          </tr>
        </table>
      </div>
    `,
			)
			.join("");
	};

	const htmlContent = `
    <div style="background-color: #f1f5f9; padding: 40px 20px; font-family: Helvetica, Arial, sans-serif;">
      <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; padding: 40px;">
        
        <div style="text-align: center; margin-bottom: 32px; border-bottom: 2px solid #f1f5f9; padding-bottom: 24px;">
          <h1 style="margin: 0; color: #0058bc; font-size: 24px; font-weight: 900; letter-spacing: -0.5px;">LabPro Connect</h1>
          <p style="margin: 4px 0 0 0; color: #94a3b8; font-size: 11px; text-transform: uppercase; letter-spacing: 2px; font-weight: 800;">Job Digest</p>
        </div>

        <div style="color: #475569; font-size: 15px; line-height: 1.6; margin-bottom: 32px;">
          <p style="margin-top: 0;">Hello,</p>
          <p>Here are the latest clinical opportunities matched to your specific laboratory parameters. The system identified <strong>${jobs.length}</strong> active positions.</p>
        </div>

        ${
					t1.length > 0
						? `
          <div style="margin-bottom: 32px;">
            <div style="background-color: #15803d; color: #ffffff; padding: 6px 12px; border-radius: 4px; font-size: 12px; font-weight: 800; display: inline-block; margin-bottom: 16px; letter-spacing: 0.5px;">
              TIER 1 MATCHES
            </div>
            ${formatJobs(t1, "#15803d")}
          </div>
        `
						: ""
				}

        ${
					t2.length > 0
						? `
          <div style="margin-bottom: 32px;">
            <div style="background-color: #0284c7; color: #ffffff; padding: 6px 12px; border-radius: 4px; font-size: 12px; font-weight: 800; display: inline-block; margin-bottom: 16px; letter-spacing: 0.5px;">
              TIER 2 MATCHES
            </div>
            ${formatJobs(t2, "#0284c7")}
          </div>
        `
						: ""
				}

        ${
					/* NEW: We now render the Tier 3 block perfectly formatted in Slate Gray! */
					t3.length > 0
						? `
          <div style="margin-bottom: 32px;">
            <div style="background-color: #94a3b8; color: #ffffff; padding: 6px 12px; border-radius: 4px; font-size: 12px; font-weight: 800; display: inline-block; margin-bottom: 16px; letter-spacing: 0.5px;">
              TIER 3 MATCHES
            </div>
            ${formatJobs(t3, "#94a3b8")}
          </div>
        `
						: ""
				}
        
        <div style="margin-top: 48px; padding-top: 24px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; line-height: 1.5;">
          This digest was automatically generated by LabPro Connect.<br/>
          You can update your email preferences in your System Settings.
        </div>
      </div>
    </div>
  `;

	try {
		await transporter.sendMail({
			from: `"LabPro Connect" <${process.env.EMAIL_USER}>`,
			to: userEmail,
			// FIX: Subject line now accurately counts all jobs sent in the payload
			subject: `Your MLS Job Digest - ${jobs.length} New Matches (${date})`,
			html: htmlContent,
		});
		console.log(`Email successfully sent to ${userEmail}`);
	} catch (error) {
		console.error("Error sending email:", error);
	}
}
