import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Resend } from "resend";
import nodemailer from "nodemailer"; // Ensure our secondary layer instance is imported

// 1. Initialize Primary Delivery Layer (Resend)
const resend = new Resend(process.env.RESEND_API_KEY);

// 2. Initialize Secondary Fallback Layer (Nodemailer SMTP / Gmail)
const fallbackTransporter = nodemailer.createTransport({
	service: "gmail",
	auth: {
		user: process.env.GMAIL_USER,
		pass: process.env.GMAIL_APP_PASSWORD, // Your secured 16-digit app password
	},
});

export async function POST(request: Request) {
	try {
		const body = await request.json();
		const { email, triggerType } = body;

		if (!email) {
			return NextResponse.json(
				{ success: false, error: "Email is required." },
				{ status: 400 },
			);
		}

		// Grab the user
		const user = await prisma.user.findUnique({ where: { email } });
		if (!user) {
			return NextResponse.json(
				{ success: false, error: "User account not found." },
				{ status: 404 },
			);
		}

		// =========================================================================
		// 🚀 UNIFIED COMPLIANCE INTERCEPTOR BLOCK (Fires for BOTH Resend & Nodemailer)
		// =========================================================================
		if (triggerType === "COMPLIANCE_ALERT") {
			const complianceHtml = `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0;">
          <div style="background: #ef4444; padding: 24px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 900; letter-spacing: -0.5px;">Compliance Alert</h1>
          </div>
          <div style="padding: 32px; background: #f8fafc;">
            <h2 style="color: #0f172a; margin-top: 0; font-size: 18px; font-weight: 800;">Action Required: MLSCN License Expired</h2>
            <p style="color: #475569; font-size: 15px; line-height: 1.6;">
              Hello ${user.name.split(" ")[0]},<br/><br/>
              Your MLSCN practicing license timeline has reached a critical state (0 Days Left). 
              Please renew your credentials immediately to maintain platform compliance and continue receiving Tier 1 job matches in your Daily Digest.
            </p>
            <div style="margin-top: 32px; text-align: center;">
              <a href="https://mlscn.gov.ng" style="background: #0f172a; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 700; display: inline-block;">
                Launch MLSCN Portal &rarr;
              </a>
            </div>
            <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; line-height: 1.5;">
              This alert was automatically generated by BenchScout Compliance Engine.
            </div>
          </div>
        </div>
      `;

			try {
				// Method A: Attempt primary deployment via Resend
				await resend.emails.send({
					from: "BenchScout <onboarding@resend.dev>",
					to: email,
					subject: "Action Required: MLSCN License Expiring",
					html: complianceHtml,
				});
			} catch (resendError) {
				console.warn(
					"Resend primary compliance mailer failed, dropping down to backup SMTP...",
					resendError,
				);

				// Method B: Fallback failover connection path using Nodemailer
				await fallbackTransporter.sendMail({
					from: '"BenchScout Compliance" <success.sholly5@gmail.com>',
					to: email,
					subject: "Action Required: MLSCN License Expiring",
					html: complianceHtml,
				});
			}

			return NextResponse.json({
				success: true,
				message:
					"Compliance email dispatched successfully through active channels.",
			});
		}

		// =========================================================================
		// STANDARD JOB DIGEST ROUTINE LOGIC
		// =========================================================================

		// Grab their top 15 highest-scoring jobs
		const topJobs = await prisma.job.findMany({
			where: { userId: user.id },
			orderBy: { score: "desc" },
			take: 15,
		});

		if (topJobs.length === 0) {
			return NextResponse.json(
				{
					success: false,
					error: "No matches found to send. Run a scan first!",
				},
				{ status: 400 },
			);
		}

		const emailHtml = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 16px;">
        <div style="text-align: center; margin-bottom: 32px; border-bottom: 2px solid #f1f5f9; padding-bottom: 24px;">
           <h1 style="margin: 0; font-size: 28px; font-weight: 900; letter-spacing: -0.5px;">
              <span style="color: #0f172a;">Bench</span><span style="color: #0058bc;">Scout</span>
           </h1>
           <p style="margin: 4px 0 0 0; color: #64748b; font-size: 13px; text-transform: uppercase; letter-spacing: 2px; font-weight: 800;">
              Job Digest
           </p>
        </div>

        <p style="color: #475569; font-size: 15px; line-height: 1.6; margin-bottom: 24px;">
          Hello ${user.name.split(" ")[0]},<br/><br/>
          Here are the latest clinical opportunities matched to your specific laboratory parameters. The system identified <strong>${topJobs.length}</strong> top positions.
        </p>
        
        ${topJobs
					.map(
						(j) => `
          <div style="border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 16px; background-color: #ffffff; border-left: 4px solid ${j.tier === 1 ? "#15803d" : j.tier === 2 ? "#0284c7" : "#94a3b8"};">
            <div style="font-weight: 800; color: #0f172a; font-size: 16px;">${j.role}</div>
            <div style="color: #0369a1; font-size: 14px; font-weight: 700; margin: 8px 0;">${j.company} • ${j.loc}</div>
            <table style="width: 100%; margin-top: 16px; border-collapse: collapse;">
              <tr>
                <td style="font-size: 13px; color: #64748b; font-weight: 600;">
                  Match Score: <strong style="color: ${j.tier === 1 ? "#15803d" : j.tier === 2 ? "#0284c7" : "#94a3b8"}; font-size: 15px;">${j.score}%</strong>
                </td>
                <td style="text-align: right;">
                  <a href="${j.url}" style="color: #0058bc; font-size: 13px; font-weight: 700; text-decoration: none;">Apply Online &rarr;</a>
                </td>
              </tr>
            </table>
          </div>
        `,
					)
					.join("")}
        
        <div style="margin-top: 48px; padding-top: 24px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; line-height: 1.5;">
          This digest was automatically generated by BenchScout.<br/>
          You can update your email preferences in System Settings.
        </div>
      </div>
    `;

		try {
			// Primary Attempt via Resend
			await resend.emails.send({
				from: "BenchScout <onboarding@resend.dev>",
				to: email,
				subject: `Your BenchScout Job Digest - ${topJobs.length} Matches`,
				html: emailHtml,
			});
		} catch (jobResendError) {
			console.warn(
				"Primary Job Digest delivery path blocked, dropping down to backup transport pipeline...",
			);

			// Fallback Failover via Nodemailer SMTP
			await fallbackTransporter.sendMail({
				from: '"BenchScout Engine" <success.sholly5@gmail.com>',
				to: email,
				subject: `Your BenchScout Job Digest - ${topJobs.length} Matches`,
				html: emailHtml,
			});
		}

		return NextResponse.json({
			success: true,
			message: "Email digest sent successfully!",
		});
	} catch (error: any) {
		console.error("Critical Email Delivery Engine Crash:", error);
		return NextResponse.json(
			{
				success: false,
				error: error.message || "Unified routing delivery crash.",
			},
			{ status: 500 },
		);
	}
}
